# Configuration file for TreasureHunt
# Created by KevinNovak

huntArea:
  world: 'world'
  x:
    min: -500
    max: 500
  y:
    min: 2
    max: 70
  z:
    min: -500
    max: 500

chestDuration: 300
maxSpawnAttempts: 3000

