# Configuration file for TreasureHunt
# Created by KevinNovak

huntArea:
  world: 'world'
  x-Range:
    min: -500
    max: 500
  y-Range:
    min: 2
    max: 70
  z-Range:
    min: -500
    max: 500

spawnInterval: 3600
chestDuration: 1800
openedChestDuration: 300

maxSpawnAttempts: 3000
minPlayersOnline: 3
maxChests: 5

dontSpawnOn:
- 6
- 8
- 9
- 10
- 11
- 31
- 32
- 37
- 38
- 39
- 40
- 50
- 51
- 55
- 59
- 63
- 65
- 68
- 69
- 75
- 76
- 77
- 83
- 90
- 104
- 105
- 106
- 107
- 115
- 116
- 117
- 119
- 127
- 131
- 132
- 140
- 141
- 142
- 143
- 175
- 209

language:
  chestSpawned: '&e[&6TreasureHunt&e] &fWord of treasure spreads across the land!'
  chestDespawned: '&e[&6TreasureHunt&e] &fA chest has faded without being found!'
  chestFound: '&e[&6TreasureHunt&e] &b{PLAYER} &fhas struck treasure!'
  alreadyFound: '&e[&6TreasureHunt&e] &7This chest has already been found by &b{PLAYER}&7!'
  tooManyChests: '&e[&6TreasureHunt&e] &7The maximum number of chests are already spawned!'