# Configuration file for TreasureHunt
# Created by KevinNovak

huntArea:
  world: 'world'
  x-Range:
    min: -500
    max: 500
  y-Range:
    min: 2
    max: 70
  z-Range:
    min: -500
    max: 500

spawnInterval: 3600
chestDuration: 1800
openedChestDuration: 300

maxSpawnAttempts: 3000
minPlayersOnline: 3
maxChests: 5

dontSpawnOn:
- 6
- 8
- 9
- 10
- 11
- 31
