# Configuration file for TreasureHunt
# Created by KevinNovak

huntItem: FILLED_MAP

huntArea:
  world: 'world'
  x-Range:
    min: -500
    max: 500
  y-Range:
    min: 4
    max: 50
  z-Range:
    min: -500
    max: 500

spawnInterval: 1800
chestDuration: 10800
openedChestDuration: 3600
announceTime:
  enabled: true
  atRemainingTimes:
    - 600
    - 300
    - 60
closestPlayer:
  enabled: true
  interval: 5

minPlayersOnline: 3
maxChests: 5

maxSpawnAttempts: 3000
maxFitItemAttempts: 3

defaultItemWeight: 100

bufferPercentage: 10

spawnUnder:
  air: true
  water: false
  lava: false

dontSpawnOn:
  - ACACIA_BUTTON
  - ACACIA_SAPLING
  - ALLIUM
  - AZALEA
  - AZURE_BLUET
  - BAMBOO
  - BAMBOO_BUTTON
  - BIG_DRIPLEAF
  - BIRCH_BUTTON
  - BIRCH_SAPLING
  - BLUE_ORCHID
  - BRAIN_CORAL
  - BRAIN_CORAL_FAN
  - BROWN_MUSHROOM
  - BUBBLE_CORAL
  - BUBBLE_CORAL_FAN
  - CARROTS
  - CHERRY_BUTTON
  - CHERRY_SAPLING
  - CHEST
  - COCOA
  - CORNFLOWER
  - CRIMSON_BUTTON
  - CRIMSON_FUNGUS
  - DANDELION
  - DANDELION_YELLOW
  - DARK_OAK_BUTTON
  - DARK_OAK_SAPLING
  - DEAD_BUSH
  - DEAD_TUBE_CORAL
  - DEAD_BRAIN_CORAL
  - DEAD_BUBBLE_CORAL
  - DEAD_FIRE_CORAL
  - DEAD_HORN_CORAL
  - DEAD_TUBE_CORAL_FAN
  - DEAD_BRAIN_CORAL_FAN
  - DEAD_BUBBLE_CORAL_FAN
  - DEAD_FIRE_CORAL_FAN
  - DEAD_HORN_CORAL_FAN
  - FERN
  - FIRE
  - FIRE_CORAL
  - FIRE_CORAL_FAN
  - FLOWERING_AZALEA
  - GRASS
  - HORN_CORAL
  - HORN_CORAL_FAN
  - JUNGLE_BUTTON
  - JUNGLE_SAPLING
  - KELP
  - LADDER
  - LARGE_FERN
  - LAVA
  - LEVER
  - LILAC
  - LILLY_OF_THE_VALLEY
  - LILLYPAD
  - MANGROVE_BUTTON
  - NETHER_WART_BLOCK
  - OAK_BUTTON
  - OAK_SAPLING
  - ORANGE_TULIP
  - OXEYE_DAISY
  - PEONY
  - PINK_PETALS
  - PINK_TULIP
  - PITCHER_PLANT
  - POINTED_DRIPSTONE
  - POLISHED_BLACKSTONE_BUTTON
  - POPPY
  - POTATOES
  - REDSTONE_TORCH
  - REDSTONE_WALL_TORCH
  - REDSTONE_WIRE
  - RED_MUSHROOM
  - RED_TULIP
  - ROSE_BUSH
  - SCULK_SENSOR
  - SEA_PICKLE
  - SIGN
  - SMALL_DRIPLEAF
  - SPRUCE_BUTTON
  - SPRUCE_SAPLING
  - STONE_BUTTON
  - SUGAR_CANE
  - SUNFLOWER
  - SWEET_BERRIES
  - TALL_GRASS
  - TALL_SEAGRASS
  - TORCH
  - TORCHFLOWER
  - TRAPPED_CHEST
  - TUBE_CORAL
  - TUBE_CORAL_FAN
  - VINE
  - WALL_SIGN
  - WALL_TORCH
  - WARPED_BUTTON
  - WARPED_FUNGUS
  - WATER
  - WHEAT
  - WHITE_TULIP
  - WITHER_ROSE

protectAgainst:
  break: true
  burn: true
  explode: true
