# Configuration file for TreasureHunt
# Created by KevinNovak

huntItem: 358

huntArea:
  world: 'world'
  x-Range:
    min: -500
    max: 500
  y-Range:
    min: 4
    max: 50
  z-Range:
    min: -500
    max: 500

spawnInterval: 1800
chestDuration: 10800
openedChestDuration: 3600
announceTime:
  enabled: true
  atRemainingTimes:
  - 600
  - 300
  - 60
closestPlayerInterval: 5

minPlayersOnline: 3
maxChests: 5

maxSpawnAttempts: 3000
maxFitItemAttempts: 3

defaultItemWeight: 100

bufferPercentage: 10

spawnUnder:
  air: true
  water: false
  lava: false

dontSpawnOn:
- 6
- 8
- 9
- 10
- 11
- 31
- 32
- 37
- 38
- 39
- 40
- 50
- 51
- 55
- 59
- 63
- 65
- 68
- 69
- 75
- 76
- 77
- 83
- 90
- 104
- 105
- 106
- 107
- 115
- 116
- 117
- 119
- 127
- 131
- 132
- 140
- 141
- 142
- 143
- 175
- 209

protectAgainst:
  break: true
  burn: true
  explode: true